export const post = [
    {
        id: 1,
        title: 'Breaking News: Team A Wins Championship!',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget ex eget justo rhoncus vestibulum.',
        category: 'Sports',
        author: 'John Doe',
        date: '2024-07-05',
        imageUrl: '../../public/1.jpg',
    },
    {
        id: 2,
        title: 'Player B Scores Record-Breaking Goal',
        content: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
        category: 'Sports',
        author: 'Jane Smith',
        date: '2024-07-04',
        imageUrl: '../../public/2.jpg',
    },
    {
        id: 3,
        title: 'Upcoming Tournament: Dates and Details',
        content: 'Nullam sed nisi nec magna malesuada dapibus. Suspendisse potenti. Aenean auctor turpis vel luctus rhoncus.',
        category: 'Sports',
        author: 'Michael Brown',
        date: '2024-07-03',
        imageUrl: '../../public/3.jpg',
    },
    {
        id: 4,
        title: 'Team C Confirmed for International Event',
        content: 'Donec rutrum, nulla sit amet viverra sagittis, ex nulla ultricies est, sed hendrerit ipsum urna et metus.',
        category: 'Sports',
        author: 'Emily Davis',
        date: '2024-07-02',
        imageUrl: '../../public/4.jpg',
    },
    {
        id: 5,
        title: 'Coach D Talks About Strategy for Next Season',
        content: 'Vestibulum ac consequat ex. Aliquam erat volutpat. Integer mollis orci nunc, nec blandit metus dictum a.',
        category: 'Sports',
        author: 'Chris Wilson',
        date: '2024-07-01',
        imageUrl: '../../public/5.jpg',
    },
    {
        id: 6,
        title: 'Player E Injury Update: Out for Rest of Season',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget ex eget justo rhoncus vestibulum.',
        category: 'Sports',
        author: 'John Doe',
        date: '2024-06-30',
        imageUrl: '../../public/6.jpg',
    },
    {
        id: 7,
        title: 'New Sponsorship Deal Signed with Company F',
        content: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
        category: 'Sports',
        author: 'Jane Smith',
        date: '2024-06-29',
        imageUrl: '../../public/7.jpg',
    },
    {
        id: 8,
        title: 'Team G Preparing for International Championship',
        content: 'Nullam sed nisi nec magna malesuada dapibus. Suspendisse potenti. Aenean auctor turpis vel luctus rhoncus.',
        category: 'Sports',
        author: 'Michael Brown',
        date: '2024-06-28',
        imageUrl: '../../public/8.jpg',
    },
    {
        id: 9,
        title: 'Upcoming Event H: Details and Schedule Announced',
        content: 'Donec rutrum, nulla sit amet viverra sagittis, ex nulla ultricies est, sed hendrerit ipsum urna et metus.',
        category: 'Sports',
        author: 'Emily Davis',
        date: '2024-06-27',
        imageUrl: '../../public/9.jpg',
    },
    {
        id: 10,
        title: 'Team I Advances to Semi-Finals in Regional Tournament',
        content: 'Vestibulum ac consequat ex. Aliquam erat volutpat. Integer mollis orci nunc, nec blandit metus dictum a.',
        category: 'Sports',
        author: 'Chris Wilson',
        date: '2024-06-26',
        imageUrl: '../../public/10.jpg',
    },
    {
        id: 11,
        title: 'Interview with Player J: Thoughts on Team Dynamics',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget ex eget justo rhoncus vestibulum.',
        category: 'Sports',
        author: 'John Doe',
        date: '2024-06-25',
        imageUrl: '../../public/1.jpg',
    },
    {
        id: 12,
        title: 'Coach K Discusses Strategy for Playoffs',
        content: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
        category: 'Sports',
        author: 'Jane Smith',
        date: '2024-06-24',
        imageUrl: '../../public/5.jpg',
    },
    {
        id: 13,
        title: 'Player L Breaks Record for Most Goals in a Season',
        content: 'Nullam sed nisi nec magna malesuada dapibus. Suspendisse potenti. Aenean auctor turpis vel luctus rhoncus.',
        category: 'Sports',
        author: 'Michael Brown',
        date: '2024-06-23',
        imageUrl: '../../public/3.jpg',
    },
    {
        id: 14,
        title: 'Team M Wins Local Tournament, Qualifies for Nationals',
        content: 'Donec rutrum, nulla sit amet viverra sagittis, ex nulla ultricies est, sed hendrerit ipsum urna et metus.',
        category: 'Sports',
        author: 'Emily Davis',
        date: '2024-06-22',
        imageUrl: '../../public/7.jpg',
    },
    {
        id: 15,
        title: 'Upcoming Event N: Tickets Now Available',
        content: 'Vestibulum ac consequat ex. Aliquam erat volutpat. Integer mollis orci nunc, nec blandit metus dictum a.',
        category: 'Sports',
        author: 'Chris Wilson',
        date: '2024-06-21',
        imageUrl: '../../public/9.jpg',
    },
]